---
abstract: ~
author:
  - 'Wes Young, <wes@barely3am.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Iodef-Pb-Format
no_index:
  directory:
    - examples
    - inc
requires:
  Iodef::Pb: 0.01
  Module::Install: 1.00
  Snort::Rule: 1.07
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
